<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="bunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Instella.Server\Instella.Server.csproj" />
  </ItemGroup>
</Project>
