<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Instella.CLI\Instella.CLI.csproj" />
  </ItemGroup>

</Project>
