// <auto-generated />
using System;
using Instella.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Instella.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927011420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Instella.Server.Data.Entities.AdminUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastTotpTimeStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.ApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageVersions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanUpload")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("PackageId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.BuildFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("BuildId", "RelativePath")
                        .IsUnique();

                    b.ToTable("BuildFiles");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.BuildInstaller", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("BuildId", "Kind")
                        .IsUnique();

                    b.ToTable("BuildInstallers");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.BuildPatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FromBuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("PatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("ToBuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToBuildId");

                    b.HasIndex("FromBuildId", "ToBuildId")
                        .IsUnique();

                    b.ToTable("BuildPatches");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.DownloadLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPatch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("Timestamp");

                    b.ToTable("DownloadLogs");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.DownloadToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("DownloadTokens");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.IpBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("IpBans");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadAccessMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PackageChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PinnedVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PinnedVersionId");

                    b.HasIndex("PackageId", "Name")
                        .IsUnique();

                    b.ToTable("PackageChannels");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PackagePublisherKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "KeyId")
                        .IsUnique();

                    b.ToTable("PackagePublisherKeys");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PackageVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Changelog")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("stable");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionKey")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "VersionString")
                        .IsUnique();

                    b.HasIndex("PackageId", "Channel", "VersionKey");

                    b.ToTable("PackageVersions");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PendingPatchJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FromBuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ToBuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromBuildId");

                    b.HasIndex("ToBuildId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("PendingPatchJobs");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.SecurityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("IpAddress");

                    b.HasIndex("Timestamp");

                    b.ToTable("SecurityEvents");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.ServerSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalBasePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("S3AccessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("S3AllowInsecureEndpoint")
                        .HasColumnType("INTEGER");

                    b.Property<string>("S3Bucket")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("S3Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("S3Preset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("S3Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("S3SecretKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("S3UrlExpiryMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.StoredFile", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstUploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PendingSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("ContentHash");

                    b.HasIndex("PendingSince");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.UploadSessionFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deduplicated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("SessionId", "RelativePath")
                        .IsUnique();

                    b.ToTable("UploadSessionFiles");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.UploadSessionInstaller", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deduplicated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("SessionId", "Kind")
                        .IsUnique();

                    b.ToTable("UploadSessionInstallers");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.UploadSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ApiKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Architecture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OS")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PackageDbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("UploadSessions", (string)null);
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.VersionBuild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Architecture")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("OS")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PatchDownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseKeyId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ReleaseManifestBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ReleaseSignature")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "OS", "Architecture")
                        .IsUnique();

                    b.ToTable("VersionBuilds");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.ApiKey", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.Package", "Package")
                        .WithMany("ApiKeys")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.BuildFile", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.VersionBuild", "Build")
                        .WithMany("Files")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Instella.Server.Data.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("ContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.BuildInstaller", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.VersionBuild", "Build")
                        .WithMany("Installers")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Instella.Server.Data.Entities.StoredFile", "StoredFile")
                        .WithMany()
                        .HasForeignKey("ContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.BuildPatch", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.VersionBuild", "FromBuild")
                        .WithMany("PatchesFrom")
                        .HasForeignKey("FromBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Instella.Server.Data.Entities.VersionBuild", "ToBuild")
                        .WithMany("PatchesTo")
                        .HasForeignKey("ToBuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromBuild");

                    b.Navigation("ToBuild");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.DownloadLog", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.VersionBuild", "Build")
                        .WithMany("DownloadLogs")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.DownloadToken", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.IpBan", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.AdminUser", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PackageChannel", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.Package", "Package")
                        .WithMany("Channels")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Instella.Server.Data.Entities.PackageVersion", "PinnedVersion")
                        .WithMany()
                        .HasForeignKey("PinnedVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Package");

                    b.Navigation("PinnedVersion");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PackagePublisherKey", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.Package", "Package")
                        .WithMany("PublisherKeys")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PackageVersion", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.Package", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PendingPatchJob", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.VersionBuild", "FromBuild")
                        .WithMany()
                        .HasForeignKey("FromBuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Instella.Server.Data.Entities.VersionBuild", "ToBuild")
                        .WithMany()
                        .HasForeignKey("ToBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromBuild");

                    b.Navigation("ToBuild");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.UploadSessionFile", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.UploadSessionRecord", "Session")
                        .WithMany("Files")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.UploadSessionInstaller", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.UploadSessionRecord", "Session")
                        .WithMany("Installers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.VersionBuild", b =>
                {
                    b.HasOne("Instella.Server.Data.Entities.PackageVersion", "Version")
                        .WithMany("Builds")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.Package", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Channels");

                    b.Navigation("PublisherKeys");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.PackageVersion", b =>
                {
                    b.Navigation("Builds");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.UploadSessionRecord", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Installers");
                });

            modelBuilder.Entity("Instella.Server.Data.Entities.VersionBuild", b =>
                {
                    b.Navigation("DownloadLogs");

                    b.Navigation("Files");

                    b.Navigation("Installers");

                    b.Navigation("PatchesFrom");

                    b.Navigation("PatchesTo");
                });
#pragma warning restore 612, 618
        }
    }
}
