using System.Text.Json;
using System.Text.Json.Serialization;
using Instella.Core.FileSystem;
using Instella.Core.Platform;

namespace Instella.Core.Installation;

/// <summary>
/// <c>instella-upgrade.json</c> at the root of the app's files: names the app's upgrade program and
/// how to run it. Generated by the <c>InstellaUpgradeProgram</c> MSBuild property of Instella.Sdk and
/// shipped as an ordinary release file, so it is signed with the app's other files. Read only through
/// <see cref="AppUpgradeDeclarations"/>, which validates it.
/// </summary>
internal sealed record AppUpgradeDeclaration
{
    /// <summary>The launch contract version the program speaks (<see cref="AppUpgradeContract.CurrentVersion"/>).</summary>
    public required int ContractVersion { get; init; }

    /// <summary>The program, relative to the install folder, as declared (see <see cref="AppUpgradeDeclarations.ProgramPathFor"/>).</summary>
    public required string Program { get; init; }

    /// <summary>Extra arguments, passed after the contract's own.</summary>
    public IReadOnlyList<string> Arguments { get; init; } = [];

    /// <summary>The time limit; the process tree is ended when it is reached.</summary>
    public int TimeoutMinutes { get; init; } = AppUpgradeContract.DefaultTimeoutMinutes;

    /// <summary>Whether the program is also run with <c>--instella-uninstall</c> before an uninstall.</summary>
    public bool HandlesUninstall { get; init; }
}

/// <summary>The file as written, before validation: every field optional so each problem gets its own message.</summary>
internal sealed record AppUpgradeDeclarationFile
{
    public int? ContractVersion { get; init; }
    public string? Program { get; init; }
    public List<string?>? Arguments { get; init; }
    public int? TimeoutMinutes { get; init; }
    public bool? HandlesUninstall { get; init; }
}

/// <summary>Source-generated JSON for <see cref="AppUpgradeDeclarationFile"/>.</summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    ReadCommentHandling = JsonCommentHandling.Skip,
    AllowTrailingCommas = true,
    WriteIndented = true)]
[JsonSerializable(typeof(AppUpgradeDeclarationFile))]
internal sealed partial class AppUpgradeDeclarationJsonContext : JsonSerializerContext;

/// <summary>The outcome of reading a declaration.</summary>
internal abstract record AppUpgradeDeclarationRead
{
    private AppUpgradeDeclarationRead() { }

    /// <summary>No declaration: the app has no upgrade program.</summary>
    public sealed record Absent : AppUpgradeDeclarationRead;

    /// <summary>A usable declaration.</summary>
    /// <param name="Declaration">The validated declaration.</param>
    /// <param name="ProgramRelativePath">The program for this platform, in canonical relative form.</param>
    public sealed record Valid(AppUpgradeDeclaration Declaration, string ProgramRelativePath) : AppUpgradeDeclarationRead;

    /// <summary>A declaration this build cannot honour.</summary>
    /// <param name="Reason">Why, naming the file.</param>
    public sealed record Refused(string Reason) : AppUpgradeDeclarationRead;
}

/// <summary>Reads and validates <see cref="AppUpgradeContract.DeclarationFileName"/>.</summary>
internal static class AppUpgradeDeclarations
{
    /// <summary>Reads the declaration at the root of <paramref name="installRoot"/>; <see cref="AppUpgradeDeclarationRead.Absent"/> when there is none.</summary>
    public static async Task<AppUpgradeDeclarationRead> ReadAsync(
        IFileSystem fs, string installRoot, TargetPlatform platform, CancellationToken ct)
    {
        var path = SafePath.Combine(installRoot, AppUpgradeContract.DeclarationFileName);
        if (!fs.Exists(path)) return new AppUpgradeDeclarationRead.Absent();
        var read = await fs.ReadAllBytesAsync(path, ct);
        if (!read.Success || read.Value is null)
            return Refuse($"cannot be read: {read.Error?.Message ?? "unknown error"}");
        return Parse(read.Value, platform);
    }

    /// <summary>Validates the bytes of a declaration.</summary>
    public static AppUpgradeDeclarationRead Parse(ReadOnlySpan<byte> json, TargetPlatform platform)
    {
        AppUpgradeDeclarationFile? file;
        try
        {
            file = JsonSerializer.Deserialize(json, AppUpgradeDeclarationJsonContext.Default.AppUpgradeDeclarationFile);
        }
        catch (JsonException ex)
        {
            return Refuse($"is not valid: {ex.Message}");
        }
        if (file is null) return Refuse("is not a JSON object");

        if (file.ContractVersion is not { } contract)
            return Refuse("has no contractVersion");
        if (contract < 1)
            return Refuse($"declares contract version {contract}, which does not exist");
        if (contract > AppUpgradeContract.CurrentVersion)
            return Refuse($"declares contract version {contract}; this installer supports up to {AppUpgradeContract.CurrentVersion}. " +
                          "Install the latest installer of the app");

        if (string.IsNullOrWhiteSpace(file.Program))
            return Refuse("names no program");
        if (!SafePath.TryNormalizeRelative(file.Program, out var normalized, out var why))
            return Refuse($"names the program '{file.Program}', which {why}");
        var program = ProgramPathFor(normalized, platform);
        if (!SafePath.IsSafeRelative(program))
            return Refuse($"names the program '{file.Program}', which is not a usable file name on this platform");
        if (InstellaOwnedPaths.IsOwned(normalized) || InstellaOwnedPaths.IsOwned(program))
            return Refuse($"names the program '{file.Program}', which belongs to Instella");

        var arguments = new List<string>();
        foreach (var arg in file.Arguments ?? [])
        {
            if (arg is null) return Refuse("has a null entry in arguments");
            if (arg.Contains('\0')) return Refuse("has an argument containing NUL");
            arguments.Add(arg);
        }

        var timeout = file.TimeoutMinutes ?? AppUpgradeContract.DefaultTimeoutMinutes;
        if (timeout is < 1 or > AppUpgradeContract.MaxTimeoutMinutes)
            return Refuse($"sets timeoutMinutes to {timeout}; it must be from 1 to {AppUpgradeContract.MaxTimeoutMinutes}");

        return new AppUpgradeDeclarationRead.Valid(new AppUpgradeDeclaration
        {
            ContractVersion = contract,
            Program = file.Program,
            Arguments = arguments,
            TimeoutMinutes = timeout,
            HandlesUninstall = file.HandlesUninstall ?? false,
        }, program);
    }

    /// <summary>
    /// The program's file for <paramref name="platform"/>: on Windows <c>.exe</c> is added when the
    /// name has no <c>.exe</c> extension; elsewhere a trailing <c>.exe</c> is removed. So
    /// <c>App.Upgrade</c> and <c>App.Upgrade.exe</c> both work everywhere.
    /// </summary>
    public static string ProgramPathFor(string program, TargetPlatform platform)
    {
        var p = program.Replace('\\', '/');
        var hasExe = p.EndsWith(".exe", StringComparison.OrdinalIgnoreCase);
        if (platform == TargetPlatform.Windows)
            return hasExe ? p : p + ".exe";
        return hasExe ? p[..^4] : p;
    }

    private static AppUpgradeDeclarationRead.Refused Refuse(string what) =>
        new($"{AppUpgradeContract.DeclarationFileName} {what}");
}
